# Form implementation generated from reading ui file 'ui_models/search_window_design.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_search_window(object):
    def setupUi(self, search_window):
        search_window.setObjectName("search_window")
        search_window.resize(450, 350)
        self.search_table = QtWidgets.QTableWidget(parent=search_window)
        self.search_table.setGeometry(QtCore.QRect(13, 50, 425, 291))
        self.search_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.search_table.setColumnCount(3)
        self.search_table.setObjectName("search_table")
        self.search_table.setRowCount(0)
        self.search_table.horizontalHeader().setVisible(False)
        self.search_table.horizontalHeader().setDefaultSectionSize(50)
        self.search_table.horizontalHeader().setMinimumSectionSize(50)
        self.search_btn = QtWidgets.QPushButton(parent=search_window)
        self.search_btn.setGeometry(QtCore.QRect(359, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.search_input = QtWidgets.QLineEdit(parent=search_window)
        self.search_input.setGeometry(QtCore.QRect(14, 10, 340, 30))
        self.search_input.setObjectName("search_input")

        self.retranslateUi(search_window)
        QtCore.QMetaObject.connectSlotsByName(search_window)

    def retranslateUi(self, search_window):
        _translate = QtCore.QCoreApplication.translate
        search_window.setWindowTitle(_translate("search_window", "Поиск"))
        self.search_btn.setText(_translate("search_window", "Поиск"))
