# Form implementation generated from reading ui file 'ui_models/welcome_window_design.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_welcome_window(object):
    def setupUi(self, welcome_window):
        welcome_window.setObjectName("welcome_window")
        welcome_window.resize(200, 160)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=welcome_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout.addWidget(self.search_btn)
        self.add_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)

        self.retranslateUi(welcome_window)
        QtCore.QMetaObject.connectSlotsByName(welcome_window)

    def retranslateUi(self, welcome_window):
        _translate = QtCore.QCoreApplication.translate
        welcome_window.setWindowTitle(_translate("welcome_window", "Hi!"))
        self.search_btn.setText(_translate("welcome_window", "Поиск организации"))
        self.add_btn.setText(_translate("welcome_window", "Добавить организацию"))
